import dogCoolingMat from '@/assets/images/products/dog_cooling_mat--thumbnail.png'
import dogCoolingMatLarge from '@/assets/images/products/dog_cooling_mat.jpg'


export default [
  {
    id: 1,
    name: 'Cooling mat',
    price: '13,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 2,
    name: 'Cooling mat',
    price: '11,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 3,
    name: 'Cooling mat',
    price: '9,49',
    dateAdded: '2019-01-19T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 4,
    name: 'Cooling mat',
    price: '15,22',
    dateAdded: '2019-01-13T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 5,
    name: 'Cooling mat',
    price: '16,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 6,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-12T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 7,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 8,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 9,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 10,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ]
  },
  {
    id: 11,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ],
    tags: ['luxury', 'splash'],
  },
  {
    id: 12,
    name: 'Cooling mat',
    price: '15,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ],
    tags: ['new', 'on-sale'],
  },
  {
    id: 13,
    name: 'Cooling mat',
    price: '115,49',
    dateAdded: '2019-01-14T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ],
    tags: ['other', 'on-sale'],
  },
  {
    id: 14,
    name: 'Super Cooling mat',
    price: '215,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ],
    tags: ['luxury', 'on-sale'],
  },
  {
    id: 15,
    name: 'Ultra Cooling mat',
    price: '422,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ],
    tags: ['new', 'splash'],
  },
  {
    id: 16,
    name: 'Cooling mat',
    price: '12,49',
    dateAdded: '2019-01-16T10:20:30Z',
    img: dogCoolingMat,
    imgFull: dogCoolingMatLarge,
    description: 'Hier komt een deel van de beschrijvende tekst die bij elk product hoort. Ook terug te vinden in het product detail.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eius..',
    imgAlt: 'Dog Cooling Mat',
    colors: [
      'white',
      'black',
      'blue',
    ],
    tags: 'splash',
  },
]